.gitignore
Added the .gitignore file to maven project to avoid showing target files and temporary files as changes.
=> added .gitignore to project

luke.sh
Thought I might share this little change I made to be able to run luke from anywhere.
=> Added LUKE_PATH env variable to luke.sh

pom.xml, src/main/java/org/apache/lucene/index/IndexGate.java, src/main/java/org/getopt/luke/Luke.java, src/main/java/org/getopt/luke/plugins/FsDirectory.java
I hope that's all needed to do the update to 5.3. It let's me open an index created by Lucene 5.3, but I am not familiar with the Luke codebase, so I hope I didn't forget anything. Hope it helps.
=> #37 Updating to Lucene 5.3

pom.xml
Fix for https://github.com/DmitryKey/luke/issues/43
=> Add Restlet Maven repository

.gitignore, luke.sh, luke_solr.sh
Fix gitignore, launch scripts.
=> Some trivial changes

pom.xml, src/main/java/org/getopt/luke/plugins/FsDirectory.java
- Updated POM
- Fixed rename method implementation in FsDirectory
=> Upgrade to Lucene 6.2.0

pom.xml
Trivial update update for Lucene 6.2.1 release. #63 
It works well in my environment. Can we release Luke 6.2.1? :)
=> Upgrade lucene version to 6.2.1

pom.xml
fixed a Maven warning because of the dynamic version. It's not as readable as before but Maven doesn't complain anymore.
=> fixed a Maven warning because of the dynamic version

.gitignore, README.md, luke.sh
Added a comment in README and luke.sh on the usage of Luke with custom codecs
=> Comment on codecs

src/main/assembly/assembly.xml
I find it rather annoying to unpack the archive and have the contents in the same folder. This PR adds a top level folder luke-${version}.
=> added top level folder to release artifact

README.md
I hope this instruction would be useful for the people who come from different programming community like Ruby/Python/Perl.
**Edit** I have also improved the existing launching luke section.
=> Update Launching Luke section.

pom.xml
No changes other than to the POM itself.
=> Updated Lucene version to 6.3.0

src/main/java/org/getopt/luke/Luke.java
Explanation : 
Method `getTermsEnum` was removed from `PrefixQuery` in favor of the parent class AutomatonQuery, see : 
https://github.com/apache/lucene-solr/commit/6a6c72992040b907f7894e63a4ff79253d02b1f5
Fix : 
search for method in all class hiearchy
Caveat : 
no unittest update for this change (it does not seems there are any tests... if am wrong, please point me to the proper direction)
=> Fix #84 NoSuchMethodException: PrefixQuery.getTermsEnum

luke.sh
Otherwise this script will fail for example when using fish shell
=> Add shebang to luke.sh

pom.xml, src/main/java/org/apache/lucene/index/IndexGate.java, src/main/java/org/getopt/luke/NoScoringScorer.java
Updated pom file, fixed to use latest Lucene APIs.
=> Upgrade to Lucene 7.2.0

src/main/java/org/getopt/luke/Luke.java, src/main/resources/xml/editcolumns.xml
@DmitryKey This is a PR for the "edit columns" after merging to the 'luke-thinlet' branch
=> Added "edit columns" to search tab

src/main/java/org/getopt/luke/Luke.java, src/main/java/thinlet/Thinlet.java, src/main/resources/xml/editcolumns.xml
@DmitryKey Added the "edit columns" dialog in the search tab.
Allows selecting and reordering columns.
=> Added editing search result table columns

src/test/java/org/apache/lucene/luke/models/documents/DocumentsImplTest.java
=> Surpress some codecs in DocumentsImplTest

src/main/java/org/apache/lucene/luke/app/IndexHandler.java, src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/OpenIndexDialogFactory.java, src/main/java/org/apache/lucene/luke/util/IndexUtils.java
=> Log stacktraces when failing open an index reader.

pom.xml, src/main/java/org/apache/lucene/luke/app/desktop/components/DocumentsPanelProvider.java, src/main/java/org/apache/lucene/luke/app/desktop/components/OverviewPanelProvider.java, src/main/java/org/apache/lucene/luke/app/desktop/components/SearchPanelProvider.java, src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/documents/TermVectorDialogFactory.java, src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/CheckIndexDialogFactory.java, src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/OptimizeIndexDialogFactory.java, src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/search/ExplainDialogProvider.java, src/main/java/org/apache/lucene/luke/app/desktop/util/MessageUtils.java, src/main/java/org/apache/lucene/luke/app/desktop/util/TextAreaPrintStream.java, src/main/java/org/apache/lucene/luke/models/analysis/AnalysisImpl.java, src/main/java/org/apache/lucene/luke/models/commits/CommitsImpl.java, src/main/java/org/apache/lucene/luke/models/documents/DocumentsImpl.java, src/main/java/org/apache/lucene/luke/models/overview/OverviewImpl.java, src/main/java/org/apache/lucene/luke/models/search/QueryParserConfig.java, src/main/java/org/apache/lucene/luke/models/search/SearchImpl.java, src/main/java/org/apache/lucene/luke/models/search/SimilarityConfig.java, src/main/java/org/apache/lucene/luke/util/IndexUtils.java, src/test/java/org/apache/lucene/luke/models/analysis/AnalysisImplTest.java, src/test/java/org/apache/lucene/luke/models/search/SearchImplTest.java
=> Add forbiddenapis maven plugin, fix codes to pass the check

src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/OpenIndexDialogFactory.java
=> #146 Show hidden files in FileChooser dialog.

luke.bat, luke.sh, src/main/java/org/apache/lucene/luke/app/desktop/components/SearchPanelProvider.java
=> Allow deep reflection 

pom.xml, src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/documents/IndexOptionsDialogFactoryImpl.java, src/main/java/org/apache/lucene/luke/models/documents/DocumentField.java, src/main/java/org/apache/lucene/luke/models/search/SearchImpl.java
Update the pom dependency, fix compiling errors.
=> Updrate Lucene version 7.6.0

luke.sh, pom.xml, src/main/java/org/apache/lucene/luke/app/desktop/components/SearchPanelProvider.java, src/main/java/org/apache/lucene/luke/app/desktop/components/SearchTabOperator.java, src/main/java/org/apache/lucene/luke/app/desktop/components/fragments/search/SortPaneProvider.java, src/main/java/org/apache/lucene/luke/models/search/Search.java, src/main/java/org/apache/lucene/luke/models/search/SearchImpl.java, src/main/java/org/apache/lucene/luke/models/search/SearchResults.java, src/main/java/org/apache/lucene/luke/util/IndexUtils.java, src/main/resources/messages.properties, src/test/java/org/apache/lucene/luke/models/documents/TermVectorsAdapterTest.java, src/test/java/org/apache/lucene/luke/models/search/SearchImplTest.java
Upgrade lucene version 8.0.0. This also add a checkbox to the Search tab to return exact hit count (for backward compatibility).
=> Upgrade lucene 8.0.0

pom.xml, src/main/java/org/apache/lucene/luke/app/DirectoryHandler.java, src/main/java/org/apache/lucene/luke/app/IndexHandler.java, src/main/java/org/apache/lucene/luke/app/desktop/components/dialog/menubar/CheckIndexDialogFactory.java, src/main/java/org/apache/lucene/luke/app/desktop/dto/documents/NewField.java, src/main/java/org/apache/lucene/luke/models/LukeModel.java, src/main/java/org/apache/lucene/luke/models/analysis/Analysis.java, src/main/java/org/apache/lucene/luke/models/analysis/AnalysisImpl.java, src/main/java/org/apache/lucene/luke/models/analysis/CustomAnalyzerConfig.java, src/main/java/org/apache/lucene/luke/models/documents/DocValuesAdapter.java, src/main/java/org/apache/lucene/luke/models/documents/DocumentField.java, src/main/java/org/apache/lucene/luke/models/documents/DocumentsImpl.java, src/main/java/org/apache/lucene/luke/models/documents/TermVectorEntry.java, src/main/java/org/apache/lucene/luke/models/documents/TermVectorsAdapter.java, src/main/java/org/apache/lucene/luke/models/overview/OverviewImpl.java, src/main/java/org/apache/lucene/luke/models/overview/TermCounts.java, src/main/java/org/apache/lucene/luke/models/overview/TopTerms.java, src/main/java/org/apache/lucene/luke/models/search/SearchImpl.java, src/main/java/org/apache/lucene/luke/models/search/SearchResults.java, src/main/java/org/apache/lucene/luke/models/tools/IndexToolsImpl.java, src/main/java/org/apache/lucene/luke/util/IndexUtils.java
Removed the dependency to FindBugs, which is no no longer maintained, and added runtime non null checks instead of the `@Nonnull` annotation.
=> Remove the dependency to FindBugs

pom.xml, src/main/java/org/apache/lucene/luke/app/desktop/PreferencesImpl.java, src/main/java/org/apache/lucene/luke/app/desktop/util/inifile/IniFile.java, src/main/java/org/apache/lucene/luke/app/desktop/util/inifile/IniFileReader.java, src/main/java/org/apache/lucene/luke/app/desktop/util/inifile/IniFileWriter.java, src/main/java/org/apache/lucene/luke/app/desktop/util/inifile/OptionMap.java, src/main/java/org/apache/lucene/luke/app/desktop/util/inifile/SimpleIniFile.java, src/main/java/org/apache/lucene/luke/app/desktop/util/inifile/SimpleIniFileReader.java, src/main/java/org/apache/lucene/luke/app/desktop/util/inifile/SimpleIniFileWriter.java, src/test/java/org/apache/lucene/luke/app/desktop/util/inifile/SimpleIniFileTest.java
Replaced ini4j (which is no longer maintained) with a simple `.ini` file parser / writer.
=> Remove the dependency to ini4j, implement ini file parser and writer.
